name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - ci_cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Đăng nhập vào Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t your-docker-image-name:latest .  # Thay your-docker-image-name bằng tên của bạn

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Bước này cần hoàn thành trước khi thực hiện deploy

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.254.142.47 << 'EOF'
            if [ ! -d "CN_CNPM" ]; then
              git clone git@github.com:hoangduy00987/CN_CNPM.git
            fi
            cd CN_CNPM
            git pull origin master
            sudo docker-compose down
            sudo docker-compose up --build -d 
            sudo docker-compose exec web python manage.py collectstatic --noinput  # Thu thập tệp tĩnh
            sudo systemctl restart gunicorn
          EOF
