name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - ci_cd

jobs:
  build:
    runs-on: ubuntu-latest
    # check code tu repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    # thiet lap moi truong
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Đăng nhập vào Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: |
          docker build -t app:latest .
          docker tag app:latest hoangduy00998/app:latest
      
      - name: Notify build outcome
        run: |
        if: failure()
        run: echo "Build failed" | mail -s "Build Notifications" hoangduy00998#gmail.com

  test: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        users: actions/checkout@v2

      - name: Run tests
        run: |
          python manage.py test

      - name: Notify test outcome
        if: failure()
        run: echo "test failed" | mail -s "Test Notification" hoangduy0998@gmail.com


  deploy_to_production:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout code
        users: actions/checkout@v2

      - name: Push Docker image to Docker hub
        run: |
          docker push hoangduy00998/app:latest

      - name: Deploy to Production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@cnpm.duytech.site "cd CN_CNPM && git pull origin main && docker-compose up --build"
